"""
Complex scenario test helpers for DeepEP low-latency kernels.

Provides:
  - test_nonuniform_tokens: dispatch+combine round-trip with asymmetric token
    distribution across ranks, generated by ``get_imbalance_token_counts``.
"""

from typing import Optional

import os
import random
import time
import torch
import torch.distributed as dist
import deep_ep
from utils import per_token_cast_back, per_token_cast_to_fp8, get_imbalance_token_counts, create_test_data, hash_tensor


def test_nonuniform_tokens(
    hidden: int,
    num_experts: int,
    num_topk: int,
    rank: int,
    num_ranks: int,
    group: dist.ProcessGroup,
    seed: int = 42,
    total_tokens: Optional[int] = None,
    imbalance_ratio: float = 1.0,
    host_jitter: bool = False,
    device_jitter: bool = False,
    expert_imbalance_ratio: float = 0.0,
) -> int:
    """Non-uniform token count dispatch+combine round-trip test.

    Computes per-rank token counts via :func:`utils.get_imbalance_token_counts`,
    allocates a Buffer sized for ``max_tokens_per_rank``, then runs dispatch+combine
    for both BF16 and FP8 paths, asserting no NaN in combined output.

    Following the pattern of ``run_performance_test``, the ``num_tokens`` argument
    to ``low_latency_dispatch`` is ``max_tokens_per_rank`` (the pre-allocated capacity),
    while each rank's actual tensor has ``current_rank_num_tokens`` rows.

    Returns:
        int: XOR of ``hash_tensor(combined_x)`` across both BF16 and FP8 paths.
            Callers can compare successive calls with the same seed to verify
            determinism (reproducibility) of the dispatch+combine pipeline.

    Args:
        hidden: Hidden dimension size.
        num_experts: Total number of experts (must be divisible by num_ranks).
        num_topk: Top-k value for expert selection.
        rank: Current rank index.
        num_ranks: Total number of ranks.
        group: The distributed process group.
        seed: Random seed passed to ``get_imbalance_token_counts``.
        total_tokens: Total token count to distribute (default: ``num_ranks * 128``).
        imbalance_ratio: Skew factor forwarded to ``get_imbalance_token_counts``
            as a float fraction (0.4 = 40%, 1.0 = 100%, 2.0 = 200%).
            Convert from the CLI integer percent convention with ``ratio / 100.0``.
        host_jitter: If True, each rank sleeps a random 0-10 ms on the host
            (via ``std::this_thread::sleep_for``, blocks the CPU thread).
        device_jitter: If True, each rank inserts a random 0-10 ms delay on the
            device (via GPU delay kernel ``tops::__nanosleep``, does not block CPU).
            Both can be enabled simultaneously.
        expert_imbalance_ratio: Hot/cold expert fraction of the top-k slots
            (0.0-1.0). 0.0 disables the hot/cold construction.
    """
    if total_tokens is None:
        total_tokens = num_ranks * 128

    assert num_experts % num_ranks == 0
    num_local_experts = num_experts // num_ranks

    # All ranks use the same seed → same per-rank count list.
    counts = get_imbalance_token_counts(num_ranks, total_tokens, imbalance_ratio, seed)
    max_tokens_per_rank = max(counts)   # buffer capacity: covers the largest rank
    current_rank_num_tokens = counts[rank]  # actual tokens this rank sends

    x, topk_idx, topk_weights = create_test_data(
        current_rank_num_tokens, hidden, num_experts, num_topk, rank, num_ranks,
        seed=seed, expert_imbalance_ratio=expert_imbalance_ratio)

    # Buffer must be sized for max_tokens_per_rank so every rank can receive the worst case.
    num_rdma_bytes = deep_ep.Buffer.get_low_latency_rdma_size_hint(
        max_tokens_per_rank, hidden, num_ranks, num_experts)
    buffer = deep_ep.Buffer(group, num_rdma_bytes=num_rdma_bytes, low_latency_mode=True,
                            num_qps_per_rank=num_experts // num_ranks,
                            allow_nvlink_for_low_latency_mode=True, explicitly_destroy=True,
                            allow_mnnvl=False)
    hash_value = 0
    try:
        for dispatch_use_fp8 in (False, True):
            cumulative_stats = torch.zeros((num_local_experts,), dtype=torch.int, device='gcu')

            eff_host_ms = random.uniform(0, 10) if host_jitter else 0.0
            eff_device_ms = random.uniform(0, 10) if device_jitter else 0.0

            # Set env vars for C++ to read (non-invasive jitter injection)
            if eff_host_ms > 0:
                os.environ['DEEP_EP_HOST_JITTER_MS'] = f'{eff_host_ms:.2f}'
            else:
                os.environ.pop('DEEP_EP_HOST_JITTER_MS', None)
            if eff_device_ms > 0:
                os.environ['DEEP_EP_DEVICE_JITTER_MS'] = f'{eff_device_ms:.2f}'
            else:
                os.environ.pop('DEEP_EP_DEVICE_JITTER_MS', None)

            if eff_host_ms > 0 or eff_device_ms > 0:
                parts = []
                if eff_host_ms > 0:
                    parts.append(f'host={eff_host_ms:.2f}ms')
                if eff_device_ms > 0:
                    parts.append(f'device={eff_device_ms:.2f}ms')
                print(f'[jitter] Rank {rank}: {"+".join(parts)} between '
                      f'SEND and RECV phases (fp8={dispatch_use_fp8})', flush=True)

            packed_recv_x, packed_recv_count, handle, event, _hook = \
                buffer.low_latency_dispatch(
                    x, topk_idx, max_tokens_per_rank, num_experts,
                    use_fp8=dispatch_use_fp8,
                    cumulative_local_expert_recv_stats=cumulative_stats,
                    async_finish=True, return_recv_hook=False)
            event.current_stream_wait()

            for i in range(num_local_experts):
                recv_count = packed_recv_count[i].item()
                assert recv_count >= 0, \
                    f'Rank {rank}: negative recv_count={recv_count} for expert {i}'

            if dispatch_use_fp8:
                packed_recv_x = (packed_recv_x[0], packed_recv_x[1].contiguous())
                simulated_gemm_x = per_token_cast_back(
                    packed_recv_x[0].view(-1, hidden),
                    packed_recv_x[1].view(-1, hidden // 128)
                ).view(packed_recv_x[0].shape)
            else:
                simulated_gemm_x = packed_recv_x.clone()

            out = torch.empty((current_rank_num_tokens, hidden),
                              dtype=torch.bfloat16, device='gcu')
            if eff_host_ms > 0:
                print(f'[jitter] Rank {rank}: host sleeping {eff_host_ms:.2f} ms before combine',
                      flush=True)
                time.sleep(eff_host_ms / 1000.0)
            combined_x, event, _hook = buffer.low_latency_combine(
                simulated_gemm_x, topk_idx, topk_weights, handle,
                async_finish=True, return_recv_hook=False, out=out)
            event.current_stream_wait()

            if current_rank_num_tokens > 0:
                nan_count = torch.isnan(combined_x).sum().item()
                assert nan_count == 0, \
                    f'Rank {rank}: combined_x has {nan_count} NaN(s) (fp8={dispatch_use_fp8})'
            hash_value ^= hash_tensor(combined_x)
    finally:
        os.environ.pop('DEEP_EP_HOST_JITTER_MS', None)
        os.environ.pop('DEEP_EP_DEVICE_JITTER_MS', None)
        buffer.destroy()
    return hash_value


def test_nonuniform_tokens_normal(
    hidden: int,
    num_experts: int,
    num_topk: int,
    rank: int,
    num_ranks: int,
    buffer: deep_ep.Buffer,
    config: deep_ep.Config,
    seed: int = 42,
    total_tokens: Optional[int] = None,
    imbalance_ratio: float = 1.0,
    host_jitter: bool = False,
    device_jitter: bool = False,
    expert_imbalance_ratio: float = 0.0,
) -> int:
    """Non-uniform token count dispatch+combine round-trip on the *normal* path.

    Same scenario as :func:`test_nonuniform_tokens` (per-rank asymmetric token
    counts from :func:`utils.get_imbalance_token_counts`), but drives the
    standard ``buffer.dispatch``/``buffer.combine`` API used by
    ``test_intranode.py`` instead of the low-latency API.  The per-rank layout
    (``num_tokens_per_rank`` / ``is_token_in_rank`` / ``num_tokens_per_expert``)
    is derived from ``buffer.get_dispatch_layout``; the caller's buffer must be
    sized for at least ``max(counts)`` tokens on any single rank, and
    ``config`` carries the caller's SM tuning.

    Returns:
        int: XOR of ``hash_tensor(combined_x)`` across BF16 and FP8 paths.
            Callers can compare successive calls with the same seed to verify
            determinism of the dispatch+combine pipeline.
    """
    if total_tokens is None:
        total_tokens = num_ranks * 128

    assert num_experts % num_ranks == 0

    # All ranks use the same seed → same per-rank count list.
    counts = get_imbalance_token_counts(num_ranks, total_tokens, imbalance_ratio, seed)
    current_rank_num_tokens = counts[rank]

    x, topk_idx, topk_weights = create_test_data(
        current_rank_num_tokens, hidden, num_experts, num_topk, rank, num_ranks,
        seed=seed, expert_imbalance_ratio=expert_imbalance_ratio)

    # Standard-path layout (num_tokens_per_rank / num_tokens_per_expert are
    # global, is_token_in_rank is (num_tokens, num_ranks)).
    num_tokens_per_rank, _, num_tokens_per_expert, is_token_in_rank, _ = \
        buffer.get_dispatch_layout(topk_idx, num_experts)

    # FP8 variant, mirroring test_intranode.test_main.
    x_e4m3 = per_token_cast_to_fp8(x) if deep_ep.Buffer.is_sm90_compiled() else None
    x_e4m3 = (x_e4m3[0], x_e4m3[1].T.contiguous().T) if x_e4m3 is not None else None

    hash_value = 0
    try:
        for dispatch_use_fp8 in (False, True):
            dispatch_x = x_e4m3 if dispatch_use_fp8 else x
            if dispatch_x is None:
                continue

            eff_host_ms = random.uniform(0, 10) if host_jitter else 0.0
            eff_device_ms = random.uniform(0, 10) if device_jitter else 0.0

            # Set env vars for C++ to read (non-invasive jitter injection)
            if eff_host_ms > 0:
                os.environ['DEEP_EP_HOST_JITTER_MS'] = f'{eff_host_ms:.2f}'
            else:
                os.environ.pop('DEEP_EP_HOST_JITTER_MS', None)
            if eff_device_ms > 0:
                os.environ['DEEP_EP_DEVICE_JITTER_MS'] = f'{eff_device_ms:.2f}'
            else:
                os.environ.pop('DEEP_EP_DEVICE_JITTER_MS', None)

            if eff_host_ms > 0 or eff_device_ms > 0:
                parts = []
                if eff_host_ms > 0:
                    parts.append(f'host={eff_host_ms:.2f}ms')
                if eff_device_ms > 0:
                    parts.append(f'device={eff_device_ms:.2f}ms')
                print(f'[jitter] Rank {rank}: {"+".join(parts)} before data send '
                      f'(notify→dispatch, fp8={dispatch_use_fp8})', flush=True)

            recv_x, recv_topk_idx, recv_topk_weights, recv_num_tokens_per_expert_list, \
                handle, _ = buffer.dispatch(
                    dispatch_x, num_tokens_per_rank=num_tokens_per_rank,
                    is_token_in_rank=is_token_in_rank,
                    num_tokens_per_expert=num_tokens_per_expert,
                    topk_idx=topk_idx, topk_weights=topk_weights,
                    config=config, async_finish=False)
            # async_finish=False: synchronous mode, data is ready on return — no wait.

            recv_x = per_token_cast_back(*recv_x) if isinstance(recv_x, tuple) else recv_x

            for i, recv_count in enumerate(recv_num_tokens_per_expert_list):
                assert recv_count >= 0, \
                    f'Rank {rank}: negative recv_count={recv_count} for expert {i}'

            if eff_host_ms > 0:
                print(f'[jitter] Rank {rank}: host sleeping {eff_host_ms:.2f} ms before combine',
                      flush=True)
                time.sleep(eff_host_ms / 1000.0)
            combined_x, combined_topk_weights, _ = buffer.combine(
                recv_x, handle=handle, topk_weights=recv_topk_weights,
                config=config, async_finish=False)
            # async_finish=False: synchronous mode, combined_x is ready on return.

            if current_rank_num_tokens > 0:
                nan_count = torch.isnan(combined_x).sum().item()
                assert nan_count == 0, \
                    f'Rank {rank}: combined_x has {nan_count} NaN(s) (fp8={dispatch_use_fp8})'
            hash_value ^= hash_tensor(combined_x)
    finally:
        os.environ.pop('DEEP_EP_HOST_JITTER_MS', None)
        os.environ.pop('DEEP_EP_DEVICE_JITTER_MS', None)
    return hash_value
